# Generated by Django 5.1.5 on 2026-01-21 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pm25', models.FloatField(help_text='Particulate Matter PM2.5')),
                ('pm10', models.FloatField(help_text='Particulate Matter PM10')),
                ('co', models.FloatField(help_text='Carbon Monoxide (ppm)')),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('iqa', models.IntegerField(blank=True, help_text='Air Quality Index', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.station')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
