# Generated by Django 6.0.1 on 2026-01-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='image_url',
            field=models.URLField(blank=True, help_text='Image illustrative de la zone', null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='pollution_causes',
            field=models.TextField(blank=True, help_text='Causes principales de la pollution', null=True),
        ),
    ]
