# Generated by Django 6.0 on 2026-01-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_station_image_url_station_pollution_causes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='no2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='o3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='so2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='source_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reading',
            name='source_type',
            field=models.CharField(choices=[('API', 'API'), ('SENSOR', 'Capteur')], default='API', max_length=10),
        ),
        migrations.AddField(
            model_name='station',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='station',
            name='station_type',
            field=models.CharField(choices=[('PHYSICAL', 'Capteur Physique'), ('VIRTUAL', 'Station Virtuelle (API)')], default='PHYSICAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='reading',
            name='co',
            field=models.FloatField(blank=True, help_text='Carbon Monoxide (ppm)', null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='pm10',
            field=models.FloatField(blank=True, help_text='Particulate Matter PM10', null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='pm25',
            field=models.FloatField(blank=True, help_text='Particulate Matter PM2.5', null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['station', '-timestamp'], name='monitoring__station_204577_idx'),
        ),
    ]
