# Generated by Django 6.0.1 on 2026-01-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_newslettersubscriber'),
        ('monitoring', '0004_sensor'),
    ]

    operations = [
    ]
