# Generated by Django 5.1.5 on 2026-02-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alertrule_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel'), ('ANNUAL', 'Annuel'), ('CUSTOM', 'Personnalisé')], max_length=20)),
                ('format', models.CharField(choices=[('PDF', 'PDF Luxe'), ('EXCEL', 'Excel (Data)')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file_path', models.CharField(max_length=255)),
                ('stations_included', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
