# Generated by Django 5.1.5 on 2026-02-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_generatedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='image',
            field=models.ImageField(blank=True, help_text='Image illustrative de la zone', null=True, upload_to='stations/'),
        ),
        migrations.AlterField(
            model_name='station',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL de l'image (obsolète)", null=True),
        ),
    ]
