# Generated by Django 5.1.5 on 2026-02-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_station_image_alter_station_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='sensors_count',
            field=models.IntegerField(default=0, help_text='Nombre de capteurs installés sur cette station'),
        ),
    ]
