# Generated by Django 5.1.5 on 2026-02-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_station_sensors_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='sensors_count',
            field=models.IntegerField(blank=True, default=0, help_text='Nombre de capteurs installés sur cette station', null=True),
        ),
    ]
