# Generated by Django 6.0.2 on 2026-02-22 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_alter_station_sensors_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='6-digit verification code', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Expiration time (15 minutes from creation)')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this code has been used')),
                ('attempts', models.IntegerField(default=0, help_text='Number of validation attempts')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of requester', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='monitoring__user_id_579503_idx'), models.Index(fields=['code', 'is_used'], name='monitoring__code_5b18a7_idx')],
            },
        ),
    ]
